---
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: leapp-packit-poc

jobs:
  - job: copr_build
    trigger: pull_request
    metadata:
      owner: "rolivier"
      project: "leapp-packit-poc"
      targets:
        - fedora-36-x86_64

  - job: copr_build
    trigger: commit
    metadata:
      owner: "rolivier"
      project: "leapp-packit-poc"
      targets:
        - fedora-36-x86_64

  - job: tests
    trigger: pull_request
    identifier: tests-7to8
    targets:
      - RHEL-7.9-ZStream
      - RHEL-7.9-rhui
    fmf_url: "https://gitlab.cee.redhat.com/rolivier/leapp-packit-poc-tests"
    fmf_ref: "main"
    use_internal_tf: True
    # tmt_plan_regex: "some-regex" < leapp needs this
    tf_post_install_script: "#!/bin/sh\nsudo sed -i s/.*ssh-rsa/ssh-rsa/ /root/.ssh/authorized_keys"

  - job: tests
    trigger: pull_request
    identifier: tests-8to9
    targets:
      - RHEL-8.6.0-Nightly 
      - RHEL-8.7.0-Nightly
      - RHEL-8.6-rhui
    fmf_url: "https://gitlab.cee.redhat.com/rolivier/leapp-packit-poc-tests"
    fmf_ref: "main"
    use_internal_tf: True
    tf_post_install_script: "#!/bin/sh\nsudo sed -i s/.*ssh-rsa/ssh-rsa/ /root/.ssh/authorized_keys"